security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        api_users_in_memory:
            id: App\Security\InMemoryApiUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_doc:
            pattern: ^/api/doc
            anonymous: true
            lazy: true

        main:
            pattern: ^/api
            stateless: true
            provider: api_users_in_memory
            guard:
                authenticators:
                    - App\Security\ApiKeyAuthenticator


    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_API }
